# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: Hacked Jekyll
description: Jekyll microtheme that looks like JSON
baseurl: ""
url: https://hacked-jekyll.netlify.app

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: Isaac Morris-Perrott
  description:
    - Hello
    - I am interested in computers, health, epistimology and philosophy
    - I aim to dive deep into my interests and share what I learn
  cv: assets/cv.pdf
  address:
    - Melbourne, Australia
  contact:
    email: imorrisperrott@gmail.com
  profiles:
    twitter: https://twitter.com/urbrainonsugar
    github: https://github.com
    youtube: https://youtube.com/@isaac-morris-perrott

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
