// AUTO-GENERATED by build.js from articles-md/*.md front matter.
// Do not edit this file by hand for those entries — edit the .md source's
// front matter instead and re-run `node build.js` (or push, if the
// post-receive hook is set up). Entries with no matching .md source (or
// whose page errored on the last build) are carried over unchanged, as
// long as their HTML file still exists.
const ARTICLES = [
  { slug: 'treatise-on-health', title: 'Treatise on Health', file: 'treatise-on-health.html', date: '2026-08-07', dateLabel: 'Aug, 2026', tags: ['health'] },
  { slug: 'coerce', title: 'Productivity and Coercion', file: 'coerce.html', date: '2026-07-20', dateLabel: 'Jul, 2026', tags: ['philosophy', 'epistimology'] },
];
