#!/usr/bin/env node
// Markdown -> HTML build pipeline for isaacmp.xyz.
//
// Reads articles-md/*.md and posts-md/*.md, renders each to HTML wrapped in
// the site's existing article/post template (matching articles/template.html
// and posts/template.html), and regenerates articles-data.js / posts-data.js
// (the registries that drive the homepage lists, search, and /tags.html)
// from the same front matter.
//
// Run manually with `node build.js`, or wire up hooks/post-receive so it
// runs automatically on push to the bare repo on the NAS.
//
// Safety:
//   - Every output file is written to a .tmp path first, then renamed into
//     place — a failed/interrupted build never leaves a half-written page.
//   - A file that fails to parse/convert is skipped (previous HTML left
//     untouched); the rest of the build continues.
//   - Only HTML files this script itself generated (marked with the
//     "AUTO-GENERATED by build.js" comment) are ever deleted or overwritten
//     during cleanup — hand-written pages like articles/poorcharlie.html are
//     never touched, even if their slug isn't in articles-md/.
//   - Registry files (articles-data.js / posts-data.js) are rebuilt from
//     front matter, but any existing entry whose HTML file still exists
//     (hand-written pages, or a page that errored *this* run but built
//     fine before) is carried over unchanged rather than dropped.

'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');
const matter = require('gray-matter');
const { marked } = require('marked');

const ROOT = __dirname;
const SITE_URL = 'https://isaacmp.xyz';
const MARKER = 'AUTO-GENERATED by build.js';

marked.setOptions({ gfm: true, breaks: false });

const TYPES = [
  {
    name: 'article',
    label: 'Articles',
    srcDir: path.join(ROOT, 'articles-md'),
    outDir: path.join(ROOT, 'articles'),
    registryFile: path.join(ROOT, 'articles-data.js'),
    registryVar: 'ARTICLES',
    urlDir: 'articles',
    backLink: '../index.html#articles',
    articleIdAttr: '',
    defaultRobots: 'index, follow'
  },
  {
    name: 'post',
    label: 'Posts',
    srcDir: path.join(ROOT, 'posts-md'),
    outDir: path.join(ROOT, 'posts'),
    registryFile: path.join(ROOT, 'posts-data.js'),
    registryVar: 'POSTS',
    urlDir: 'posts',
    backLink: '../index.html#posts',
    articleIdAttr: ' id="post-body"',
    defaultRobots: 'index, follow'
  }
];

// ---------- small helpers ----------

function escapeHtml(str) {
  return String(str == null ? '' : str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function jsStringEscape(str) {
  return String(str == null ? '' : str).replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

// gray-matter/js-yaml auto-casts unquoted YAML dates (date: 2026-08-06) into
// JS Date objects — normalize either that or a plain string back to
// 'YYYY-MM-DD' (or pass a partial 'YYYY-MM' straight through).
function normalizeDate(value) {
  if (value instanceof Date) return value.toISOString().slice(0, 10);
  return String(value == null ? '' : value).trim();
}

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

// '2026-08-06' -> 'Aug 6, 2026' ; '2026-08' -> 'Aug, 2026'
function formatDatetimeLabel(iso) {
  const parts = iso.split('-');
  const mi = parts.length >= 2 ? parseInt(parts[1], 10) - 1 : NaN;
  if (Number.isNaN(mi) || mi < 0 || mi > 11) return iso;
  if (parts.length >= 3) return `${MONTHS[mi]} ${parseInt(parts[2], 10)}, ${parts[0]}`;
  return `${MONTHS[mi]}, ${parts[0]}`;
}

// '2026-08-06' or '2026-08' -> 'Aug, 2026' (used for the homepage list's
// dateLabel, unless the front matter provides an explicit override)
function formatDateLabel(iso) {
  const parts = iso.split('-');
  const mi = parts.length >= 2 ? parseInt(parts[1], 10) - 1 : NaN;
  if (Number.isNaN(mi) || mi < 0 || mi > 11) return iso;
  return `${MONTHS[mi]}, ${parts[0]}`;
}

function tagChips(tags) {
  if (!tags || !tags.length) return '';
  const chips = tags
    .map(t => `<a class="tag" href="/tags.html?t=${encodeURIComponent(t)}">${escapeHtml(t)}</a>`)
    .join('');
  return `<span class="tags">${chips}</span>`;
}

function listMarkdownFiles(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter(f => f.endsWith('.md') && !f.startsWith('_'))
    .sort();
}

// Atomic write: build to <path>.tmp, then rename over the real path. A
// crash or thrown error between these two lines leaves the live file
// exactly as it was; the rename itself is atomic on the same filesystem.
function writeFileAtomic(destPath, content) {
  fs.mkdirSync(path.dirname(destPath), { recursive: true });
  const tmpPath = destPath + '.tmp';
  fs.writeFileSync(tmpPath, content, 'utf8');
  fs.renameSync(tmpPath, destPath);
}

// ---------- page template (mirrors articles/template.html & posts/template.html) ----------

function renderPage(type, meta, bodyHtml, srcRelPath) {
  const url = `${SITE_URL}/${type.urlDir}/${meta.slug}.html`;
  const titleEsc = escapeHtml(meta.title);
  const descEsc = escapeHtml(meta.description);
  const robots = meta.robots || type.defaultRobots;
  const timeDisplay = formatDatetimeLabel(meta.date);
  const footer = type.name === 'post' ? '\n\n  <p><a href="index.html">&larr; all posts</a></p>' : '';
  // match the 4-space indent the rest of the site's hand-written .article-content bodies use
  const indentedBody = bodyHtml
    .replace(/\n$/, '')
    .split('\n')
    .map(line => (line ? `    ${line}` : line))
    .join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<!-- ${MARKER} from ${srcRelPath} — do not edit this file directly, edit the source .md instead -->
<script>(function(){try{var t=localStorage.getItem('theme');if(t==='light'||t==='dark')document.documentElement.setAttribute('data-theme',t);}catch(e){}})();</script>
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>${titleEsc} — Isaac</title>
<meta name="description" content="${descEsc}">
<link rel="canonical" href="${url}">
<meta name="robots" content="${robots}">

<meta property="og:type" content="article">
<meta property="og:title" content="${titleEsc}">
<meta property="og:description" content="${descEsc}">
<meta property="og:url" content="${url}">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="${titleEsc}">
<meta name="twitter:description" content="${descEsc}">

<meta name="theme-color" content="#F5F2EA">
<meta name="theme-color" content="#17171A" media="(prefers-color-scheme: dark)">

<link rel="icon" href="../favicon.svg" type="image/svg+xml">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,600;1,8..60,400&display=swap" rel="stylesheet">
<link rel="stylesheet" href="../style.css">

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "headline": "${titleEsc}",
  "datePublished": "${meta.date}",
  "author": { "@type": "Person", "name": "Isaac Morris-Perrott", "url": "${SITE_URL}/" }
}
</script>
</head>
<body>

<main>
  <a href="${type.backLink}" class="back">&larr; isaacmp.xyz</a>

  <article class="article-content"${type.articleIdAttr}>
    <header class="article-header">
      <h3>${titleEsc}</h3>
      <p class="article-meta"><time datetime="${meta.date}">${timeDisplay}</time> ${tagChips(meta.tags)}</p>
    </header>

${indentedBody}
  </article>${footer}
</main>

<script src="/search.js"></script>
<script src="/theme.js"></script>
</body>
</html>
`;
}

// ---------- registry (articles-data.js / posts-data.js) ----------

function loadExistingRegistry(type) {
  if (!fs.existsSync(type.registryFile)) return [];
  const src = fs.readFileSync(type.registryFile, 'utf8');
  try {
    // Top-level `const`/`let` don't become properties of the vm context
    // object (same reason `window.FOO` doesn't work for a top-level `const
    // FOO` in a browser <script> — see search.js) — appending the variable
    // name as a trailing expression and reading the script's completion
    // value sidesteps that instead of relying on the sandbox object.
    const wrapped = `${src}\n${type.registryVar};`;
    const result = vm.runInNewContext(wrapped, {}, { timeout: 1000, filename: type.registryFile });
    return Array.isArray(result) ? result : [];
  } catch (err) {
    console.error(`  ! could not parse existing ${path.basename(type.registryFile)} (${err.message}) — treating as empty`);
    return [];
  }
}

function toRegistryEntry(type, meta) {
  if (type.name === 'article') {
    return {
      slug: meta.slug,
      title: meta.title,
      file: `${meta.slug}.html`,
      date: meta.date,
      dateLabel: meta.dateLabel,
      tags: meta.tags
    };
  }
  return {
    slug: meta.slug,
    title: meta.title,
    date: meta.date,
    tags: meta.tags
  };
}

function serializeTags(tags) {
  if (!tags || !tags.length) return '[]';
  return `[${tags.map(t => `'${jsStringEscape(t)}'`).join(', ')}]`;
}

function serializeRegistry(type, entries) {
  const sorted = [...entries].sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0));

  const lines = sorted.map(e => {
    if (type.name === 'article') {
      return `  { slug: '${jsStringEscape(e.slug)}', title: '${jsStringEscape(e.title)}', file: '${jsStringEscape(e.file)}', date: '${jsStringEscape(e.date)}', dateLabel: '${jsStringEscape(e.dateLabel)}', tags: ${serializeTags(e.tags)} },`;
    }
    return `  { slug: '${jsStringEscape(e.slug)}', title: '${jsStringEscape(e.title)}', date: '${jsStringEscape(e.date)}', tags: ${serializeTags(e.tags)} },`;
  });

  const srcGlob = `${path.basename(type.srcDir)}/*.md`;
  return (
    `// AUTO-GENERATED by build.js from ${srcGlob} front matter.\n` +
    `// Do not edit this file by hand for those entries — edit the .md source's\n` +
    `// front matter instead and re-run \`node build.js\` (or push, if the\n` +
    `// post-receive hook is set up). Entries with no matching .md source (or\n` +
    `// whose page errored on the last build) are carried over unchanged, as\n` +
    `// long as their HTML file still exists.\n` +
    `const ${type.registryVar} = [\n${lines.join('\n')}\n];\n`
  );
}

// ---------- build one content type ----------

function buildType(type) {
  const files = listMarkdownFiles(type.srcDir);
  const built = [];
  const errors = [];
  const knownSlugs = new Set();

  for (const file of files) {
    const slug = file.replace(/\.md$/, '');
    knownSlugs.add(slug);
    const srcPath = path.join(type.srcDir, file);
    const srcRelPath = path.relative(ROOT, srcPath);
    const outPath = path.join(type.outDir, `${slug}.html`);

    try {
      const raw = fs.readFileSync(srcPath, 'utf8');
      const parsed = matter(raw);
      const fm = parsed.data || {};

      if (!fm.title || !String(fm.title).trim()) throw new Error('missing required "title" in front matter');
      if (!fm.date) throw new Error('missing required "date" in front matter');

      const date = normalizeDate(fm.date);
      const meta = {
        slug,
        title: String(fm.title).trim(),
        date,
        dateLabel: fm.dateLabel ? String(fm.dateLabel) : formatDateLabel(date),
        tags: Array.isArray(fm.tags) ? fm.tags.map(String) : [],
        description: fm.description ? String(fm.description) : '',
        robots: fm.robots ? String(fm.robots) : null
      };

      const bodyHtml = marked.parse(parsed.content || '');
      const html = renderPage(type, meta, bodyHtml, srcRelPath);

      writeFileAtomic(outPath, html);
      built.push(meta);
      console.log(`  ✓ ${slug}`);
    } catch (err) {
      errors.push({ file: srcRelPath, message: err.message });
      console.error(`  ✗ ${srcRelPath}: ${err.message}`);
    }
  }

  const removed = reconcileOutputDir(type, knownSlugs);

  // Registry: fresh entries from this run's successful builds, plus any
  // existing entry whose slug wasn't freshly rebuilt this run but whose
  // HTML file still exists on disk. That covers two cases identically:
  //   - genuinely hand-written pages (no .md source at all), and
  //   - a page that built fine on some earlier run but errored *this* run
  //     (its HTML is deliberately left untouched, so its listing should be
  //     too — otherwise it'd still be a live page that's vanished from the
  //     homepage/search/tags, which is worse than just leaving it alone).
  // Reconciliation above already deleted anything that's genuinely gone, so
  // "HTML still exists" is exactly the right test here.
  const existing = loadExistingRegistry(type);
  const builtSlugs = new Set(built.map(m => m.slug));
  const carriedOver = existing.filter(
    e => e && e.slug && !builtSlugs.has(e.slug) && fs.existsSync(path.join(type.outDir, `${e.slug}.html`))
  );
  const finalEntries = [...built.map(m => toRegistryEntry(type, m)), ...carriedOver];
  writeFileAtomic(type.registryFile, serializeRegistry(type, finalEntries));

  return { built, errors, removed, carriedOver: carriedOver.length };
}

// Deletes only HTML files this script previously generated (carries the
// AUTO-GENERATED marker) whose .md source no longer exists — so a renamed
// or deleted .md file doesn't leave an orphaned page live, while
// hand-written pages are never touched regardless of their slug.
function reconcileOutputDir(type, knownSlugs) {
  if (!fs.existsSync(type.outDir)) return [];
  const removed = [];
  for (const entry of fs.readdirSync(type.outDir)) {
    if (!entry.endsWith('.html')) continue;
    const slug = entry.replace(/\.html$/, '');
    if (knownSlugs.has(slug)) continue;
    const fullPath = path.join(type.outDir, entry);
    let content;
    try {
      content = fs.readFileSync(fullPath, 'utf8');
    } catch (err) {
      continue;
    }
    if (content.includes(MARKER)) {
      fs.unlinkSync(fullPath);
      removed.push(entry);
      console.log(`  − removed orphaned ${path.join(type.urlDir, entry)} (no matching .md source)`);
    }
  }
  return removed;
}

// ---------- main ----------

function main() {
  const results = [];
  for (const type of TYPES) {
    console.log(`\nBuilding ${type.label.toLowerCase()} (${path.basename(type.srcDir)}/ -> ${path.basename(type.outDir)}/)...`);
    const files = listMarkdownFiles(type.srcDir);
    if (!files.length) {
      console.log(`  (no .md files found in ${path.basename(type.srcDir)}/)`);
    }
    results.push({ type, result: buildType(type) });
  }

  let totalBuilt = 0, totalErrors = 0, totalRemoved = 0;
  console.log('\nSummary');
  for (const { type, result } of results) {
    totalBuilt += result.built.length;
    totalErrors += result.errors.length;
    totalRemoved += result.removed.length;
    console.log(
      `  ${type.label}: ${result.built.length} built, ${result.errors.length} error(s), ` +
      `${result.removed.length} removed, ${result.carriedOver} entr${result.carriedOver === 1 ? 'y' : 'ies'} carried over unchanged`
    );
  }
  console.log(`  Total: ${totalBuilt} built, ${totalErrors} error(s), ${totalRemoved} removed\n`);

  if (totalErrors > 0) process.exitCode = 1;
}

main();
