// AUTO-GENERATED by build.js from posts-md/*.md front matter.
// Do not edit this file by hand for those entries — edit the .md source's
// front matter instead and re-run `node build.js` (or push, if the
// post-receive hook is set up). Entries with no matching .md source (or
// whose page errored on the last build) are carried over unchanged, as
// long as their HTML file still exists.
const POSTS = [
  { slug: 'dust-mites', title: 'Dust mites', date: '2026-08-19', tags: ['health'] },
  { slug: 'the-body-should-not-be-an-ecosystem', title: 'The human body should not be an ecosystem', date: '2026-08-13', tags: ['health', 'philosophy', 'transhumanism'] },
  { slug: 'potato-post', title: 'I love Potatoes', date: '2026-08-08', tags: ['food', 'diet', 'health'] },
  { slug: 'thoughts-on-you-and-your-research-speech', title: 'My thoughts on - You and Your Research - a speech by Richard Hamming', date: '2026-08-06', tags: ['life', 'productivity'] },
];
