// AUTO-GENERATED by build.js from posts-md/*.md front matter.
// Do not edit this file by hand for those entries — edit the .md source's
// front matter instead and re-run `node build.js` (or push, if the
// post-receive hook is set up). Entries with no matching .md source (or
// whose page errored on the last build) are carried over unchanged, as
// long as their HTML file still exists.
const POSTS = [
  { slug: 'thoughts-on-you-and-your-research-speech', title: 'My thoughts on:You and Your Research. A speech by Richard Hemming', date: '2026-08-06', tags: ['life', 'productivity'] },
];
